---
- name: Install WordPress, MySQL, Nginx, and PHP-FPM
  hosts: wordpress-server
  remote_user: mutonby
  # remote_user: user
  # become: yes
  become_method: sudo

  roles:
    - common
    - mysql
    - nginx
    - php-fpm
    - wordpress
