---
- name: Checking dependencies
  apt: 
    name: "{{ item }}"
    state: present
  with_items:
  - python-dev
  - build-essential
  - python-pip
  - libmysqlclient-dev
  become: true

- name: Install the python mysql module
  pip: name=MySQL-python
  become: true
